# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bee576c8e508867bdb91482048c43ee4e3a0c62826f743ac7e093c8e1005852db36acbbe20530ff018da16206528b8673831ae01404429911e023d9306a28719

test:
  secret_key_base: 2a571faf2d1d1b071a1b6cb8a4e70de5749b536d98fb92d304ce371fde465a562855c0953773c2f217fc5ff79a44e10856291c5f9c33c8fdf4cc2cb8916eed70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
